#!/usr/bin/env python3
"""Deterministic documentation consistency checks.

Layout: PLAN.md (the only roadmap and task list), STATUS.md (snapshot),
DECISIONS.md + docs/decisions/, docs/ (reference), docs/evidence/ (durable
findings; retired IDs in docs/evidence/retired.tsv).

Checks:
  1. Evidence: record filenames, duplicate IDs across records and
     retired.tsv, and the generated INDEX.md being current.
  2. RE-NNN cited in any tracked text file but neither a record nor retired.
  3. Decisions: filenames, duplicates, every D-NNN.md listed in DECISIONS.md,
     and D-NNN cited anywhere without a record.
  4. Local Markdown links in every tracked .md file: the target exists, and
     an #anchor into a Markdown file matches one of its headings.
  5. No tracked file references a deleted document or directory.
  6. No "PLAN.md <retired label>" references (PLAN.md has no such section).
  7. One task list: Markdown checkboxes appear only in PLAN.md.
  8. STATUS.md stays a snapshot: at most 4 KiB.
  9. No Nintendo-derived file is tracked: no ROM, pack, save or other
     binary, no image or audio/video outside the original XMB artwork
     (psp-game/xmb/, psp-asset-viewer/xmb/; D-037, docs/xmb-assets.md),
     and no ROM-generated table (a generated header or a known generated
     path; D-048). Golden captures are committed as pixel hashes only.

Exits 1 and prints one line per problem; exits 0 with a summary otherwise.
Run after any documentation change (see the `documentation` skill).

Usage: python3 tools/docs/validate_docs.py
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
THIS = Path(__file__).resolve()

RE_ID_RE = re.compile(r"\bRE-(\d{3})\b")
D_ID_RE = re.compile(r"\bD-(\d{3})\b")
MD_LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)\)|!\[[^\]]*\]\(([^)\s]+)\)")
TEXT_SUFFIXES = {".md", ".rs", ".py", ".sh", ".toml", ".yml", ".yaml", ".tsv", ".json", ".txt"}

# Removed in the documentation reorganisation; nothing may point at them.
DELETED_PATHS = [
    "TODO.md",
    "docs/porting-status.md",
    "porting-status.md",
    "plans/rendering",
    "plans/gameplay",
    "docs/images",
    "docs/ssb-architecture.md",
    "docs/reverse-engineering.md",
    "docs/agent-rendering.md",
    "docs/visual-regression.md",
]
DELETED_RE = re.compile(
    "|".join(r"(?<![\w/.-])" + re.escape(p) + r"(?![\w-])" for p in DELETED_PATHS)
)
PLAN_LABEL_RE = re.compile(r"PLAN\.md`?(?:'s)?\s+`?(?:R[0-3]|P[0-5]|M[0-4]|F1|G[0-5]|[TC]\d)\b")
CHECKBOX_RE = re.compile(r"^\s*[-*] \[[ xX]\]", re.M)

# Check 9: what may never be tracked. ROM-derived tables are generated at
# build time into OUT_DIR by crates/ssb-tablegen (never into the source tree).
ORIGINAL_MEDIA_DIRS = ("psp-game/xmb/", "psp-asset-viewer/xmb/")
MEDIA_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".tga", ".ppm",
                  ".pgm", ".tif", ".tiff", ".at3", ".pmf", ".mp4", ".wav", ".aiff",
                  ".mp3", ".ogg"}
BINARY_SUFFIXES = {".z64", ".n64", ".v64", ".rom", ".pak", ".sav", ".bin", ".raw",
                   ".pbp", ".prx", ".elf", ".o"}
GENERATED_PATHS = {
    "crates/ssb-game/src/motion/scripts.rs",
    "crates/ssb-rom/src/anim_table.rs",
    "crates/ssb-game/src/colanim_scripts.rs",
    "crates/ssb-game/src/computer/scripts.rs",
    "crates/ssb-game/src/spgame/stat_flags.rs",
}
GENERATED_HEADER_RE = re.compile(
    r"^// (?:@generated|Generated by tools/gen-|Generated at build time)", re.M)


def tracked_files():
    out = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, capture_output=True, check=True)
    for name in out.stdout.decode().split("\0"):
        if name:
            p = ROOT / name
            if p.is_file():
                yield p


def slug(heading):
    """GitHub's heading anchor."""
    h = re.sub(r"[`*_]|<[^>]+>", "", heading.strip().lower())
    h = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", h)
    h = re.sub(r"[^\w\- ]", "", h)
    return h.replace(" ", "-")


_anchor_cache = {}


def anchors(path):
    if path not in _anchor_cache:
        text = path.read_text(encoding="utf-8", errors="ignore")
        text = re.sub(r"```.*?```", "", text, flags=re.S)
        seen = {}
        result = set()
        for m in re.finditer(r"^#{1,6}\s+(.*?)\s*#*\s*$", text, re.M):
            s = slug(m.group(1))
            n = seen.get(s, 0)
            seen[s] = n + 1
            result.add(s if n == 0 else f"{s}-{n}")
        _anchor_cache[path] = result
    return _anchor_cache[path]


def main():
    problems = []
    files = [p for p in tracked_files() if p.suffix in TEXT_SUFFIXES]
    texts = {p: p.read_text(encoding="utf-8", errors="ignore") for p in files}

    # --- 1: evidence records and retired IDs ---
    re_dir = ROOT / "docs" / "evidence" / "re"
    re_defined = {}
    for f in sorted(re_dir.glob("*.md")):
        m = re.fullmatch(r"RE-(\d{3})\.md", f.name)
        if not m:
            problems.append(f"evidence: unexpected filename {f.relative_to(ROOT)}")
            continue
        re_defined[m.group(1)] = f
    retired = set()
    retired_path = ROOT / "docs" / "evidence" / "retired.tsv"
    if retired_path.exists():
        for line in retired_path.read_text(encoding="utf-8").splitlines():
            if not line.strip() or line.startswith("#"):
                continue
            cols = line.split("\t")
            m = re.fullmatch(r"RE-(\d{3})", cols[0])
            if len(cols) != 4 or not m:
                problems.append(f"retired.tsv: malformed row {line[:60]!r}")
                continue
            num = m.group(1)
            if num in retired:
                problems.append(f"retired.tsv: RE-{num} listed twice")
            if num in re_defined:
                problems.append(f"RE-{num} is both a record and retired")
            retired.add(num)
    gen = subprocess.run([sys.executable, str(ROOT / "tools/docs/gen_evidence_index.py"), "--check"],
                         cwd=ROOT, capture_output=True, text=True)
    if gen.returncode != 0:
        problems.append("docs/evidence/INDEX.md is stale; run tools/docs/gen_evidence_index.py")

    # --- 2: RE IDs cited anywhere ---
    known_re = set(re_defined) | retired
    for f, text in texts.items():
        if f.parent == re_dir:
            continue
        for num in sorted({m.group(1) for m in RE_ID_RE.finditer(text)} - known_re):
            problems.append(f"{f.relative_to(ROOT)}: RE-{num} has no record and is not retired")

    # --- 3: decisions ---
    d_dir = ROOT / "docs" / "decisions"
    d_defined = {}
    for f in sorted(d_dir.glob("*.md")):
        m = re.fullmatch(r"D-(\d{3})\.md", f.name)
        if not m:
            problems.append(f"decisions: unexpected filename {f.relative_to(ROOT)}")
            continue
        d_defined[m.group(1)] = f
    decisions_index = (ROOT / "DECISIONS.md").read_text(encoding="utf-8")
    for num in d_defined:
        if f"(docs/decisions/D-{num}.md)" not in decisions_index:
            problems.append(f"DECISIONS.md does not list D-{num}")
    for f, text in texts.items():
        for num in sorted({m.group(1) for m in D_ID_RE.finditer(text)} - set(d_defined)):
            problems.append(f"{f.relative_to(ROOT)}: D-{num} has no decision record")

    # --- 4: local Markdown links and anchors ---
    md_files = [f for f in files if f.suffix == ".md"]
    for f in md_files:
        text = re.sub(r"```.*?```", "", texts[f], flags=re.S)
        text = re.sub(r"`[^`\n]*`", "", text)
        for m in MD_LINK_RE.finditer(text):
            target = m.group(1) or m.group(2)
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            path_part, _, anchor = target.partition("#")
            dest = f if not path_part else (f.parent / path_part).resolve()
            if not dest.exists():
                problems.append(f"broken link in {f.relative_to(ROOT)}: {target}")
                continue
            if anchor and dest.suffix == ".md" and anchor not in anchors(dest):
                problems.append(f"broken anchor in {f.relative_to(ROOT)}: {target}")

    # --- 5/6/7: deleted paths, PLAN.md labels, checkboxes ---
    for f, text in texts.items():
        if f == THIS:
            continue
        rel = f.relative_to(ROOT)
        for m in DELETED_RE.finditer(text):
            problems.append(f"{rel}: references deleted {m.group(0)}")
        for m in PLAN_LABEL_RE.finditer(text):
            problems.append(f"{rel}: '{m.group(0)}' names a retired plan label; cite the RE/D record")
        if f.suffix == ".md" and f.name != "PLAN.md" and CHECKBOX_RE.search(text):
            problems.append(f"{rel}: task checkboxes outside PLAN.md (one task list)")

    # --- 8: STATUS.md size ---
    size = (ROOT / "STATUS.md").stat().st_size
    if size > 4096:
        problems.append(f"STATUS.md is {size} bytes; keep the snapshot under 4 KiB")

    # --- 9: no Nintendo-derived files tracked ---
    listed = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, capture_output=True, check=True)
    for name in filter(None, listed.stdout.decode().split("\0")):
        suffix = Path(name).suffix.lower()
        if suffix in BINARY_SUFFIXES:
            problems.append(f"{name}: ROM, pack, save or binary file tracked")
        elif suffix in MEDIA_SUFFIXES and not name.startswith(ORIGINAL_MEDIA_DIRS):
            problems.append(f"{name}: image or media file outside the original XMB artwork; "
                            "golden captures are committed as hashes (tests/golden/hashes.tsv)")
        elif name in GENERATED_PATHS:
            problems.append(f"{name}: ROM-generated table tracked; it is generated at build time")
        elif suffix == ".rs":
            path = ROOT / name
            head = path.read_bytes()[:512].decode("utf-8", "ignore") if path.is_file() else ""
            if GENERATED_HEADER_RE.search(head):
                problems.append(f"{name}: generated source tracked; generate it at build time")

    if problems:
        print(f"{len(problems)} problem(s) found:\n")
        for p in problems:
            print(" -", p)
        return 1
    print(f"OK: {len(re_defined)} RE records ({len(retired)} retired IDs), "
          f"{len(d_defined)} D records, {len(md_files)} Markdown files checked.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
