// Generated by tools/gen-anim-table.py from refs/ssb-decomp-re.
// Do not edit by hand; re-run the generator instead.

/// The statuses carried, in slot order.
pub const SLOT_NAMES: [&str; SLOT_COUNT] = ["Dash", "Turn", "RunBrake", "Squat", "SquatRv", "Landing", "Pass"];

#[rustfmt::skip]
pub const FIGHTER_ANIMS: [FighterAnims; 27] = [
    FighterAnims { name: "Mario",    files: [ 504,  507,  506,  515,  517,  518,  519] },
    FighterAnims { name: "Fox",      files: [ 647,  650,  649,  658,  660,  661,  662] },
    FighterAnims { name: "Donkey",   files: [ 805,  808,  807,  816,  818,  819,  820] },
    FighterAnims { name: "Samus",    files: [ 958,  961,  960,  969,  971,  972,  973] },
    FighterAnims { name: "Luigi",    files: [1104,  507, 1105,  515,  517,  518,  519] },
    FighterAnims { name: "Link",     files: [1120, 1123, 1122, 1131, 1133, 1134, 1135] },
    FighterAnims { name: "Yoshi",    files: [1820, 1823, 1822, 1830, 1832, 1833, 1834] },
    FighterAnims { name: "Captain",  files: [1517, 1520, 1519, 1528, 1530, 1531, 1532] },
    FighterAnims { name: "Kirby",    files: [1264, 1267, 1266, 1278, 1280, 1281, 1282] },
    FighterAnims { name: "Pikachu",  files: [1962, 1965, 1964, 1973, 1975, 1976, 1977] },
    FighterAnims { name: "Purin",    files: [1463, 1491, 1483, 1487, 1280, 1478, 1480] },
    FighterAnims { name: "Ness",     files: [1669, 1672, 1671, 1680, 1682, 1683, 1684] },
    FighterAnims { name: "Boss",     files: [2098, 2098, 2098, 2098, 2098, 2098, 2098] },
    FighterAnims { name: "MMario",   files: [ 504,  507,  506,  515,  517,  518,  519] },
    FighterAnims { name: "NMario",   files: [ 504,  507,  506,  515,  517,  518,  519] },
    FighterAnims { name: "NFox",     files: [ 647,  650,  649,  658,  660,  661,  662] },
    FighterAnims { name: "NDonkey",  files: [ 805,  808,  807,  816,  818,  819,  820] },
    FighterAnims { name: "NSamus",   files: [ 958,  961,  960,  969,  971,  972,  973] },
    FighterAnims { name: "NLuigi",   files: [1104,  507, 1105,  515,  517,  518,  519] },
    FighterAnims { name: "NLink",    files: [1120, 1123, 1122, 1131, 1133, 1134, 1135] },
    FighterAnims { name: "NYoshi",   files: [1820, 1823, 1822, 1830, 1832, 1833, 1834] },
    FighterAnims { name: "NCaptain", files: [1517, 1520, 1519, 1528, 1530, 1531, 1532] },
    FighterAnims { name: "NKirby",   files: [1264, 1267, 1266, 1278, 1280, 1281, 1282] },
    FighterAnims { name: "NPikachu", files: [1962, 1965, 1964, 1973, 1975, 1976, 1977] },
    FighterAnims { name: "NPurin",   files: [1463, 1491, 1483, 1487, 1280, 1478, 1480] },
    FighterAnims { name: "NNess",    files: [1669, 1672, 1671, 1680, 1682, 1683, 1684] },
    FighterAnims { name: "GDonkey",  files: [ 805,  808,  807,  816,  818,  819,  820] },
];

/// Lengths the decompilation's own C sources give for the same files.
/// `romtool anims --verify` checks the ROM against these.
#[rustfmt::skip]
pub const EXPECTED_FRAMES: [[u16; SLOT_COUNT]; 27] = [
    [ 23,  12,  23,   8,  12,   7,  25],  // Mario
    [ 22,  12,  18,   8,  10,   8,  25],  // Fox
    [ 31,  12,  30,   6,   8,   8,  25],  // Donkey
    [ 23,  12,  21,   7,   7,   8,  25],  // Samus
    [ 27,  12,  32,   8,  12,   7,  25],  // Luigi
    [ 31,  12,  25,   4,   4,   8,  24],  // Link
    [ 27,  12,  28,   8,  10,   7,  25],  // Yoshi
    [ 29,  12,  30,   8,  10,  11,  30],  // Captain
    [ 24,  12,  23,   8,  10,   8,  25],  // Kirby
    [ 23,  12,  20,   4,   8,   8,  24],  // Pikachu
    [ 25,  12,  18,   8,  10,   8,  25],  // Purin
    [ 23,  12,  23,   4,   8,   7,  24],  // Ness
    [  0,   0,   0,   0,   0,   0,   0],  // Boss
    [ 23,  12,  23,   8,  12,   7,  25],  // MMario
    [ 23,  12,  23,   8,  12,   7,  25],  // NMario
    [ 22,  12,  18,   8,  10,   8,  25],  // NFox
    [ 31,  12,  30,   6,   8,   8,  25],  // NDonkey
    [ 23,  12,  21,   7,   7,   8,  25],  // NSamus
    [ 27,  12,  32,   8,  12,   7,  25],  // NLuigi
    [ 31,  12,  25,   4,   4,   8,  24],  // NLink
    [ 27,  12,  28,   8,  10,   7,  25],  // NYoshi
    [ 29,  12,  30,   8,  10,  11,  30],  // NCaptain
    [ 24,  12,  23,   8,  10,   8,  25],  // NKirby
    [ 23,  12,  20,   4,   8,   8,  24],  // NPikachu
    [ 25,  12,  18,   8,  10,   8,  25],  // NPurin
    [ 23,  12,  23,   4,   8,   7,  24],  // NNess
    [ 31,  12,  30,   6,   8,   8,  25],  // GDonkey
];
