#!/usr/bin/env python3
"""Translate FTStatusDesc.sflags from the decomp's status headers.

These are gameplay constants, not ROM assets. Fail on gaps or unknown values.
Usage: python3 tools/gen-stat-flags.py [--refs refs/ssb-decomp-re]
"""
import argparse
import importlib.util
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("motions", ROOT / "tools/gen-motion-scripts.py")
motions = importlib.util.module_from_spec(spec)
spec.loader.exec_module(motions)


def rows(path, ids):
    parts = re.split(r"//\s*Status (\d+) \(0x[0-9A-Fa-f]+\):[^\n]*", path.read_text())
    result = {}
    for i in range(1, len(parts), 2):
        body = motions.COMMENT_RE.sub(" ", parts[i + 1]).strip().lstrip("{").strip()
        values = [s.strip() for s in body.split(",")[:7]]
        assert len(values) == 7 and values[2] == "0", (path, values)
        smash = {"FALSE": 0, "TRUE": 1}[values[3]]
        air = {"nMPKineticsGround": 0, "nMPKineticsAir": 1}[values[4]]
        projectile = {"FALSE": 0, "TRUE": 1}[values[5]]
        result[int(parts[i])] = (smash << 12) | (air << 11) | (projectile << 10) | ids[values[6]]
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--refs", type=Path, default=ROOT / "refs/ssb-decomp-re")
    args = parser.parse_args()
    ids = motions.enum_values((args.refs / "src/ft/ftdef.h").read_text(), "FTStatusAttackIndex")
    # Some source rows use motion-enum symbols in the status-ID field.
    # Preserve their numeric values rather than correcting their spelling.
    ids.update(motions.enum_values((args.refs / "src/ft/ftdef.h").read_text(), "FTMotionAttackIndex"))
    out = ["// Generated by tools/gen-stat-flags.py. Do not edit by hand.\n"]
    tables = [("COMMON", args.refs / "src/ft/ftcommon/ftcommonstatus.h", 0)]
    tables += [(name.upper(), args.refs / "src/ft/ftchar" / header, 220)
               for name, _, header in motions.FIGHTERS]
    for name, path, start in tables:
        flags = rows(path, ids)
        assert sorted(flags) == list(range(start, max(flags) + 1)), path
        vals = list(flags.values())
        out.append(f"#[rustfmt::skip]\npub const {name}: [u16; {len(vals)}] = [\n")
        for i in range(0, len(vals), 12):
            out.append("    " + ", ".join(f"0x{v:04X}" for v in vals[i:i+12]) + ",\n")
        out.append("];\n\n")
    text = "".join(out).rstrip() + "\n"
    dest = ROOT / "crates/ssb-game/src/spgame/stat_flags.rs"
    dest.write_text(text)


if __name__ == "__main__":
    main()
