#!/usr/bin/env python3
"""Generate ssb-game's CPU input scripts from the decompilation.

`dFTComputerPlayerInputScripts` (`src/ft/ftcomputer.c`) is the table of
byte scripts `ftComputerUpdateInputs` interprets: each event is a command
byte (opcode in the high nibble, wait in the low) and, for the stick
events, one value byte. The scripts are written with the
`FTCOMPUTER_EVENT_*` macros of `src/ft/ftdef.h`; this script expands them
to bytes so the table is reproducible rather than hand-typed. The table's
order is the pointer table's, which swaps scripts 24 and 25.

Usage:
    tools/gen-computer-scripts.py [--refs refs/ssb-decomp-re] [--out FILE]
"""
import argparse
import os
import re
import sys

PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)


def enum_values(src, name):
    body = re.search(r"typedef enum " + name + r"\s*\{(.*?)\}", src, re.S).group(1)
    out, nxt = {}, 0
    for item in COMMENT_RE.sub(" ", body).split(","):
        item = item.strip()
        if not item:
            continue
        if "=" in item:
            key, val = (x.strip() for x in item.split("=", 1))
            nxt = int(val, 0)
        else:
            key = item
        out[key] = nxt
        nxt += 1
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--refs", default=os.path.join(PROJECT, "refs/ssb-decomp-re"))
    ap.add_argument("--out", default="-")
    args = ap.parse_args()
    ftdef = open(os.path.join(args.refs, "src/ft/ftdef.h")).read()
    src = COMMENT_RE.sub(" ", open(os.path.join(args.refs, "src/ft/ftcomputer.c")).read())
    names = enum_values(ftdef, "FTComputerCommandKind")
    names.update({
        "I_CONTROLLER_RANGE_MAX": 80,
        "FTCOMPUTER_STICK_AUTOFULL": 0x7F,
        "FTCOMPUTER_STICK_AUTOHALF": 0x80,
    })

    def value(expr):
        expr = expr.strip()
        for k, v in sorted(names.items(), key=lambda kv: -len(kv[0])):
            expr = re.sub(r"\b" + k + r"\b", str(v), expr)
        if not re.fullmatch(r"[\d\s()+\-*/xXa-fA-F]+", expr):
            raise ValueError(f"unexpanded expression {expr!r}")
        return int(eval(expr.replace("/", "//"))) & 0xFF

    def instruction(k, t):
        return ((value(k) << 4) & 0xF0) | (value(t) & 0x0F)

    scripts = {}
    for m in re.finditer(r"u8 dFTComputerPlayerInputScript(\d+)\[\s*\]\s*=\s*\{(.*?)\};", src, re.S):
        body, out = m.group(2), []
        for ev in re.finditer(r"FTCOMPUTER_EVENT_(\w+)\(([^()]*(?:\([^()]*\)[^()]*)*)\)", body):
            kind = ev.group(1)
            argv = [a.strip() for a in ev.group(2).split(",")] if ev.group(2).strip() else []
            if kind == "INSTRUCTION":
                out.append(instruction(argv[0], argv[1]))
            elif kind == "STICK_X":
                out += [instruction("nFTComputerCommandStickX", argv[1]), value(argv[0])]
            elif kind == "STICK_Y":
                out += [instruction("nFTComputerCommandStickY", argv[1]), value(argv[0])]
            elif kind == "PKTHUNDER":
                out.append(0xF3)
            elif kind == "END":
                out.append(0xFF)
            else:
                raise ValueError(f"unknown event {kind}")
        # Bare bytes between events (a wait's operand) are not used by any
        # script; refuse them rather than drop them.
        stripped = re.sub(r"FTCOMPUTER_EVENT_\w+\(([^()]*(?:\([^()]*\)[^()]*)*)\)", "", body)
        if stripped.replace(",", "").strip():
            raise ValueError(f"script {m.group(1)}: bytes outside events: {stripped!r}")
        scripts[int(m.group(1))] = out

    table = re.search(r"u8 \*dFTComputerPlayerInputScripts\[\s*\]\s*=\s*\{(.*?)\};", src, re.S).group(1)
    order = [int(n) for n in re.findall(r"dFTComputerPlayerInputScript(\d+)", table)]

    w = []
    w.append("// Generated by tools/gen-computer-scripts.py from refs/ssb-decomp-re.\n")
    w.append("// Do not edit by hand; re-run the generator instead.\n\n")
    w.append("/// `dFTComputerPlayerInputScripts`, in pointer-table order (which swaps\n")
    w.append("/// scripts 24 and 25).\n")
    w.append("#[rustfmt::skip]\n")
    w.append(f"pub static INPUT_SCRIPTS: [&[u8]; {len(order)}] = [\n")
    for n in order:
        bytes_ = ", ".join(f"0x{b:02X}" for b in scripts[n])
        w.append(f"    &[{bytes_}], // Script{n}\n")
    w.append("];\n\n")
    kinds = enum_values(ftdef, "FTComputerInputKind")
    w.append("/// `nFTComputerInput*`: [`INPUT_SCRIPTS`] indices by name.\n")
    w.append("pub mod input {\n")
    for k, v in kinds.items():
        const = re.sub(r"(?<!^)(?=[A-Z])", "_", k[len("nFTComputerInput"):]).upper()
        const = re.sub(r"_(\d)", r"\1", const)
        w.append(f"    pub const {const}: usize = {v};\n")
    w.append("}\n")
    out = sys.stdout if args.out == "-" else open(args.out, "w")
    out.write("".join(w))


if __name__ == "__main__":
    main()
